[package]
name = "cosmic-tweaks"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
ashpd = "0.8.1"
dirs = "5.0.1"
i18n-embed-fl = "0.8"
once_cell = "1.19.0"
open = "5.1.2"
ron = "0.8.1"
rust-embed = "8.3.0"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = ["wayland", "wgpu", "tokio"]

[dependencies.i18n-embed]
version = "0.14"
features = ["fluent-system", "desktop-requester"]

[dependencies.cosmic-panel-config]
git = "https://github.com/pop-os/cosmic-panel"

[dependencies.cosmic-app-list]
git = "https://github.com/edfloreshz/cosmic-applets"

[dependencies.serde]
version = "1.0.196"
features = ["derive"]

[dependencies.tokio]
version = "1.35.1"
features = ["macros", "fs", "rt"]
